SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Indexes */

DROP INDEX ACCOUNTID ON LOTTERY_ORDER;
DROP INDEX ROUNDID ON LOTTERY_ORDER;
DROP INDEX ORDERID ON LOTTERY_ORDER_DETAIL;
DROP INDEX LOTTERYTYPE ON LOTTERY_ROUND;
DROP INDEX ROUNDID ON LOTTERY_ROUND_ITEM;
DROP INDEX NAME_GROUP ON TASK_SCHEDULE_JOB;
DROP INDEX ACCOUNTID ON TRADE_INFO;



/* Drop Tables */

DROP TABLE LOTTERY_ORDER_DETAIL;
DROP TABLE LOTTERY_ORDER;
DROP TABLE TRADE_INFO;
DROP TABLE ACCOUNT_DETAIL;
DROP TABLE LOTTERY_ORDER_DETAIL;
DROP TABLE LOTTERY_ORDER;
DROP TABLE TRADE_INFO;
DROP TABLE ACCOUNT_DETAIL;
DROP TABLE ACCOUNT_INFO;
DROP TABLE ACCOUNT_INFO;
DROP TABLE ACCOUNT_INFO;
DROP TABLE ACCOUNT_INFO;
DROP TABLE ACCOUNT_RECORD;
DROP TABLE LOTTERY_GAME;
DROP TABLE LOTTERY_ITEM;
DROP TABLE LOTTERY_ITEM;
DROP TABLE LOTTERY_ROUND_ITEM;
DROP TABLE LOTTERY_ROUND;
DROP TABLE LOTTERY_ROUND_ITEM;
DROP TABLE LOTTERY_ROUND;
DROP TABLE LOTTERY_SERVICE;
DROP TABLE NOTICE_INFO;
DROP TABLE NOTICE_INFO;
DROP TABLE OFFACCOUNT_INFO;
DROP TABLE OFFACCOUNT_INFO;
DROP TABLE SUBACCOUNT_INFO;
DROP TABLE TASK_SCHEDULE_JOB;
DROP TABLE T_S_TIMETASK;




/* Create Tables */

CREATE TABLE ACCOUNT_DETAIL
(
	ACCOUNTID INT NOT NULL AUTO_INCREMENT COMMENT 'Accountid',
	USERID INT NOT NULL COMMENT 'UserID',
	USERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL COMMENT 'UserName',
	LIMITED DOUBLE(18,2) DEFAULT 0.00 COMMENT 'Limited',
	RATIO DOUBLE(18,4) DEFAULT 0.00 COMMENT 'Ratio',
	PERCENTAGE DOUBLE(18,4) DEFAULT 0.00 COMMENT 'Percentage',
	STATE CHAR DEFAULT '1' COMMENT 'State',
	SUPUSERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' COMMENT 'SupUserName',
	LEVEL VARCHAR(20) DEFAULT '<EMPTY STRING>' COMMENT 'Level',
	OFFTYPE CHAR COMMENT 'OffType',
	ATTRIBUTE1 VARCHAR(20) COMMENT 'Attribute1',
	MONEY DECIMAL(19,2) DEFAULT 0.00 COMMENT 'Money',
	ATTRIBUTE2 VARCHAR(20) COMMENT 'Attribute2',
	PRIMARY KEY (ACCOUNTID),
	UNIQUE (USERNAME)
) COMMENT = 'account_detail' DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE ACCOUNT_DETAIL
(
	ACCOUNTID INT NOT NULL AUTO_INCREMENT COMMENT 'ACCOUNTID',
	USERID INT NOT NULL COMMENT 'USERID',
	USERNAME VARCHAR(20) NOT NULL UNIQUE COMMENT 'USERNAME',
	LIMITED DOUBLE(18,2) DEFAULT 0.00 COMMENT 'LIMITED',
	RATIO DOUBLE(18,4) DEFAULT 0.0000 COMMENT 'RATIO',
	PERCENTAGE DOUBLE(18,4) DEFAULT 0.0000 COMMENT 'PERCENTAGE',
	STATE CHAR(1) DEFAULT '1' COMMENT 'STATE',
	SUPUSERNAME VARCHAR(20) COMMENT 'SUPUSERNAME',
	LEVEL VARCHAR(20) COMMENT 'LEVEL',
	OFFTYPE CHAR(1) COMMENT 'OFFTYPE',
	MONEY DECIMAL(19,2) DEFAULT 0.00 COMMENT 'MONEY',
	ATTRIBUTE1 VARCHAR(20) COMMENT 'ATTRIBUTE1',
	ATTRIBUTE2 VARCHAR(20) COMMENT 'ATTRIBUTE2',
	BUDGET VARCHAR(100) COMMENT 'BUDGET',
	PRIMARY KEY (ACCOUNTID)
) COMMENT = 'account_detail';


CREATE TABLE ACCOUNT_INFO
(
	USERID INT NOT NULL AUTO_INCREMENT COMMENT 'USERID',
	USERNAME VARCHAR(20) NOT NULL COMMENT 'USERNAME',
	AUSERNAME VARCHAR(20) NOT NULL COMMENT 'AUSERNAME',
	PASSWORD VARCHAR(50) NOT NULL COMMENT 'PASSWORD',
	LIMITED DOUBLE(18,2) DEFAULT 0.00 COMMENT 'LIMITED',
	RATIO DOUBLE(18,4) DEFAULT 0.0000 COMMENT 'RATIO',
	IP VARCHAR(20) COMMENT 'IP',
	INPUTDATE DATETIME COMMENT 'INPUTDATE',
	UPDATEIP VARCHAR(20) COMMENT 'UPDATEIP',
	UPDATEDATE DATETIME COMMENT 'UPDATEDATE',
	STATE CHAR(1) NOT NULL COMMENT 'STATE',
	SUPUSERNAME VARCHAR(20) NOT NULL COMMENT 'SUPUSERNAME',
	LEVEL VARCHAR(20) COMMENT 'LEVEL',
	PHONE VARCHAR(20) COMMENT 'PHONE',
	WEBCHAT VARCHAR(30) COMMENT 'WEBCHAT',
	PRIMARY KEY (USERID)
) COMMENT = 'account_info';


CREATE TABLE ACCOUNT_INFO
(
	USERID INT NOT NULL AUTO_INCREMENT COMMENT 'USERID',
	USERNAME VARCHAR(20) NOT NULL COMMENT 'USERNAME',
	AUSERNAME VARCHAR(20) NOT NULL COMMENT 'AUSERNAME',
	PASSWORD VARCHAR(50) NOT NULL COMMENT 'PASSWORD',
	LIMITED DOUBLE(18,2) DEFAULT 0.00 COMMENT 'LIMITED',
	RATIO DOUBLE(18,4) DEFAULT 0.0000 COMMENT 'RATIO',
	IP VARCHAR(20) COMMENT 'IP',
	INPUTDATE DATETIME COMMENT 'INPUTDATE',
	UPDATEIP VARCHAR(20) COMMENT 'UPDATEIP',
	UPDATEDATE DATETIME COMMENT 'UPDATEDATE',
	STATE CHAR(1) NOT NULL COMMENT 'STATE',
	SUPUSERNAME VARCHAR(20) NOT NULL COMMENT 'SUPUSERNAME',
	LEVEL VARCHAR(20) COMMENT 'LEVEL',
	PHONE VARCHAR(20) COMMENT 'PHONE',
	WEBCHAT VARCHAR(30) COMMENT 'WEBCHAT',
	PRIMARY KEY (USERID)
) COMMENT = 'account_info';


CREATE TABLE ACCOUNT_INFO
(
	USERID INT NOT NULL AUTO_INCREMENT COMMENT 'USERID',
	USERNAME VARCHAR(20) NOT NULL COMMENT 'USERNAME',
	AUSERNAME VARCHAR(20) NOT NULL COMMENT 'AUSERNAME',
	PASSWORD VARCHAR(50) NOT NULL COMMENT 'PASSWORD',
	LIMITED DOUBLE(18,2) DEFAULT 0.00 COMMENT 'LIMITED',
	RATIO DOUBLE(18,4) DEFAULT 0.0000 COMMENT 'RATIO',
	IP VARCHAR(20) COMMENT 'IP',
	INPUTDATE DATETIME COMMENT 'INPUTDATE',
	UPDATEIP VARCHAR(20) COMMENT 'UPDATEIP',
	UPDATEDATE DATETIME COMMENT 'UPDATEDATE',
	STATE CHAR(1) NOT NULL COMMENT 'STATE',
	SUPUSERNAME VARCHAR(20) NOT NULL COMMENT 'SUPUSERNAME',
	LEVEL VARCHAR(20) COMMENT 'LEVEL',
	PHONE VARCHAR(20) COMMENT 'PHONE',
	WEBCHAT VARCHAR(30) COMMENT 'WEBCHAT',
	PRIMARY KEY (USERID)
) COMMENT = 'account_info';


CREATE TABLE ACCOUNT_INFO
(
	ACCOUNTID INT NOT NULL AUTO_INCREMENT COMMENT '用户流水号',
	USERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL COMMENT '用户名',
	AUSERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL COMMENT '别名（昵称）',
	PASSWORD VARCHAR(50) DEFAULT '<EMPTY STRING>' NOT NULL COMMENT '密码',
	LIMITED DOUBLE(18,2) DEFAULT 0.00 COMMENT '限额',
	RATIO DOUBLE(18,4) DEFAULT 0.00 COMMENT '洗码比',
	IP VARCHAR(20) DEFAULT '<EMPTY STRING>' COMMENT 'IP地址',
	INPUTDATE DATETIME COMMENT '新增时间',
	UPDATEIP VARCHAR(20) DEFAULT '<EMPTY STRING>' COMMENT '修改IP',
	UPDATEDATE DATETIME COMMENT '修改时间',
	STATE CHAR NOT NULL COMMENT '状态',
	SUPUSERID VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL COMMENT '上级编号',
	LEVEL VARCHAR(20) DEFAULT '<EMPTY STRING>' COMMENT '级别',
	PHONE VARCHAR(20) COMMENT '电话',
	WEBCHAT VARCHAR(30) COMMENT '微信',
	USERMONEY DECIMAL(19,2) COMMENT '账户余额',
	OFFTYPE VARCHAR(10) COMMENT '账户状态',
	PERCENTAGE DOUBLE(18,4) COMMENT '代理占比',
	QUERY VARCHAR(100) COMMENT '权限',
	BUDGET VARCHAR(100) COMMENT 'BUDGET',
	CODE VARCHAR(6) COMMENT '邀请码',
	SFCODE VARCHAR(30) COMMENT '安全码',
	BANKID VARCHAR(100) COMMENT '银行用户名',
	BANKNAME VARCHAR(100) COMMENT '银行名称',
	BANKADDRESS VARCHAR(100) COMMENT '开户行',
	BANKACCOUNT VARCHAR(100) COMMENT '银行账号',
	PRIMARY KEY (ACCOUNTID)
) COMMENT = 'account_info' DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE ACCOUNT_RECORD
(
	RECORDID INT(11) NOT NULL UNIQUE COMMENT '记录流水号',
	ACCOUNTID INT(11) NOT NULL COMMENT '用户流水号',
	INPUTTIME DATETIME COMMENT '登录时间',
	IP VARCHAR(30) COMMENT 'IP',
	OUTTIME DATETIME COMMENT '登出时间',
	LEVEL VARCHAR(4) COMMENT '级别',
	OFFTYPE VARCHAR(4) COMMENT '账户类型'
) COMMENT = 'account_record';


CREATE TABLE LOTTERY_GAME
(
	SID INT(11) NOT NULL UNIQUE COMMENT 'sid',
	GAMETYPE VARCHAR(4) COMMENT 'gametype',
	GAMENAME VARCHAR(100) COMMENT 'gamename',
	GAMETERM VARCHAR(11) COMMENT 'gameterm',
	GAMERATE VARCHAR(4) COMMENT 'gamerate',
	GAMENUMBER VARCHAR(30) COMMENT 'gamenumber',
	GAMELOBBYNO VARCHAR(20) COMMENT 'gamelobbyno',
	GAMELOBBYNAME VARCHAR(50) COMMENT 'gamelobbyname',
	GAMETIME VARCHAR(20) COMMENT 'gametime'
) COMMENT = 'lottery_game';


CREATE TABLE LOTTERY_ITEM
(
	-- 流水号
	ITEMID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ItemId',
	-- 游戏类型：01玉米籽
	LOTTERYTYPE VARCHAR(10) NOT NULL COMMENT 'LotteryType',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT 'ItemNo',
	-- 投注项名称
	ITEMNAME VARCHAR(50) COMMENT 'ItemName',
	-- 投注项类型：01广西快乐十分，02番摊玉米籽
	ITEMTYPE VARCHAR(10) COMMENT 'ItemType',
	-- 类别，如特码、色、单双、大小等
	ITEMGROUP VARCHAR(20) COMMENT 'ItemGroup',
	-- 游戏界面显示的赔率
	ITEMSCALE DOUBLE(18,4) NOT NULL COMMENT 'ItemScale',
	-- 派彩赔率
	ITEMODDS DOUBLE(18,4) COMMENT 'ItemOdds',
	-- 抽水比例
	ITEMBONUS DOUBLE(18,4) COMMENT 'ItemBonus',
	-- 下注项中文名称
	ITEMNAMECN VARCHAR(50) COMMENT 'ItemNameCN',
	PRIMARY KEY (ITEMID)
) COMMENT = 'lottery_item';


CREATE TABLE LOTTERY_ITEM
(
	-- 流水号
	ITEMID INT NOT NULL AUTO_INCREMENT COMMENT '流水号',
	-- 游戏类型：01玉米籽
	LOTTERYTYPE VARCHAR(10) NOT NULL COMMENT '游戏类型：01玉米籽',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT '投注项编号',
	-- 投注项名称
	ITEMNAME VARCHAR(50) COMMENT '投注项名称',
	-- 投注项类型：01广西快乐十分，02番摊玉米籽
	ITEMTYPE VARCHAR(10) COMMENT '投注项类型：01广西快乐十分，02番摊玉米籽',
	-- 类别，如特码、色、单双、大小等
	ITEMGROUP VARCHAR(20) COMMENT '类别，如特码、色、单双、大小等',
	-- 游戏界面显示的赔率
	ITEMSCALE DOUBLE(18,4) NOT NULL COMMENT '游戏界面显示的赔率',
	-- 派彩赔率
	ITEMODDS DOUBLE(18,4) COMMENT '派彩赔率',
	-- 抽水比例
	ITEMBONUS DOUBLE(18,4) COMMENT '抽水比例',
	PRIMARY KEY (ITEMID)
) COMMENT = 'lottery_item';


CREATE TABLE LOTTERY_ORDER
(
	-- 投注单ID
	ORDERID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'OrderId',
	-- 游戏ID
	ROUNDID INT NOT NULL COMMENT 'RoundId',
	-- 账户ID
	ACCOUNTID INT NOT NULL COMMENT 'AccountId',
	-- 投注金额
	ORDERAMOUNT DOUBLE(18,2) COMMENT 'OrderAmount',
	-- 代理提成
	COMMISIONAMOUNT DOUBLE(18,2) COMMENT 'CommisionAmount',
	ORDERTIME DATETIME NOT NULL COMMENT 'OrderTime',
	-- 中奖金额
	PRIZEAMOUNT DOUBLE(18,2) COMMENT 'PrizeAmount',
	-- 实际到手奖金
	ACTUALAMOUNT DOUBLE(18,2) COMMENT 'ActualAmount',
	-- 抽水返利
	RETURNAMOUNT DOUBLE(18,2) COMMENT 'ReturnAmount',
	-- 中奖时间
	PRIZETIME DATETIME COMMENT 'PrizeTime',
	-- 帐号余额
	ACCOUNTAMOUNT DECIMAL(19,2) COMMENT 'AccountAmount',
	PRIMARY KEY (ORDERID)
) COMMENT = 'lottery_order';


CREATE TABLE LOTTERY_ORDER
(
	-- 投注单ID
	ORDERID INT NOT NULL AUTO_INCREMENT COMMENT '投注单ID',
	-- 游戏ID
	ROUNDID INT NOT NULL COMMENT '游戏ID',
	-- 帐户ID
	ACCOUNTID INT NOT NULL COMMENT '帐户ID',
	-- 投注金额
	ORDERAMOUNT DOUBLE(18,2) COMMENT '投注金额',
	-- 代理提成
	COMMISIONAMOUNT DOUBLE(18,2) COMMENT '代理提成',
	ORDERTIME DATETIME NOT NULL COMMENT 'ORDERTIME',
	-- 中奖金额
	PRIZEAMOUNT DOUBLE(18,2) COMMENT '中奖金额',
	-- 实际到手奖金
	ACTUALAMOUNT DOUBLE(18,2) COMMENT '实际到手奖金',
	-- 抽水返利
	RETURNAMOUNT DOUBLE(18,2) COMMENT '抽水返利',
	SYSTEMAMOUNT DOUBLE(18,2) COMMENT 'SYSTEMAMOUNT',
	-- 中奖时间
	PRIZETIME DATETIME COMMENT '中奖时间',
	-- 帐号余额
	ACCOUNTAMOUNT DECIMAL(19,2) COMMENT '帐号余额',
	PRIMARY KEY (ORDERID)
) COMMENT = 'lottery_order';


CREATE TABLE LOTTERY_ORDER_DETAIL
(
	-- 投注单ID
	ORDERID INT NOT NULL COMMENT '投注单ID',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT '投注项编号',
	-- 赔率
	ITEMSCALE DOUBLE(18,4) COMMENT '赔率',
	-- 抽水比例
	ITEMBONUS DOUBLE(18,4) COMMENT '抽水比例',
	-- 投注金额
	DETAILAMOUNT DOUBLE(18,2) COMMENT '投注金额',
	-- 中奖金额
	PRIZEAMOUNT DOUBLE(18,2) COMMENT '中奖金额',
	-- 实际到手奖金
	ACTUALAMOUNT DOUBLE(18,2) COMMENT '实际到手奖金',
	-- 抽水返利
	RETURNAMOUNT DOUBLE(18,2) COMMENT '抽水返利',
	PRIMARY KEY (ORDERID, ITEMNO)
) COMMENT = 'lottery_order_detail';


CREATE TABLE LOTTERY_ORDER_DETAIL
(
	-- 投注单ID
	ORDERID INT NOT NULL COMMENT 'OrderId',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT 'ItemNo',
	-- 派彩赔率
	ITEMODDS DOUBLE(18,4) COMMENT 'ItemOdds',
	-- 抽水比例
	ITEMBONUS DOUBLE(18,4) COMMENT 'ItemBonus',
	-- 投注金额
	DETAILAMOUNT DOUBLE(18,2) COMMENT 'DetailAmount',
	-- 中奖金额
	PRIZEAMOUNT DOUBLE(18,2) COMMENT 'PrizeAmount',
	-- 实际到手奖金
	ACTUALAMOUNT DOUBLE(18,2) COMMENT 'ActualAmount',
	-- 抽水返利
	RETURNAMOUNT DOUBLE(18,2) COMMENT 'ReturnAmount',
	PRIMARY KEY (ORDERID, ITEMNO),
	UNIQUE (ORDERID, ITEMNO)
) COMMENT = 'lottery_order_detail';


CREATE TABLE LOTTERY_ROUND
(
	-- 游戏ID
	ROUNDID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'RoundId',
	-- 游戏类型：01玉米籽
	LOTTERYTYPE VARCHAR(10) NOT NULL COMMENT 'LotteryType',
	-- 期次
	LOTTERYTERM VARCHAR(20) NOT NULL COMMENT 'LotteryTerm',
	-- 开出之号码
	RESULTSTR VARCHAR(100) COMMENT 'ResultStr',
	-- 游戏开始时间
	STARTTIME DATETIME COMMENT 'StartTime',
	-- 游戏开奖时间
	ENDTIME DATETIME COMMENT 'EndTime',
	-- 游戏状态：Open开盘中，Close已封盘，End已结束
	ROUNDSTATUS VARCHAR(10) NOT NULL COMMENT 'RoundStatus',
	-- 开奖时间
	OPENTIME DATETIME COMMENT 'OpenTime',
	-- 封盘时间
	CLOSETIME DATETIME COMMENT 'CloseTime',
	-- 广西快乐十分开奖结果
	ORIGINRESULT VARCHAR(100) COMMENT 'OriginResult',
	PRIMARY KEY (ROUNDID),
	UNIQUE (LOTTERYTYPE, LOTTERYTERM)
) COMMENT = 'lottery_round';


CREATE TABLE LOTTERY_ROUND
(
	-- 游戏ID
	ROUNDID INT NOT NULL AUTO_INCREMENT COMMENT '游戏ID',
	-- 游戏类型：01玉米籽
	LOTTERYTYPE VARCHAR(10) NOT NULL COMMENT '游戏类型：01玉米籽',
	-- 期次
	LOTTERYTERM VARCHAR(20) NOT NULL COMMENT '期次',
	-- 开出之号码
	RESULTSTR VARCHAR(100) COMMENT '开出之号码',
	-- 游戏开始时间
	STARTTIME DATETIME COMMENT '游戏开始时间',
	-- 游戏开奖时间
	ENDTIME DATETIME COMMENT '游戏开奖时间',
	-- 游戏状态：Open开盘中，Close已封盘，End已结束
	ROUNDSTATUS VARCHAR(10) NOT NULL COMMENT '游戏状态：Open开盘中，Close已封盘，End已结束',
	OPENTIME DATETIME COMMENT 'OPENTIME',
	CLOSETIME DATETIME COMMENT 'CLOSETIME',
	ORIGINRESULT VARCHAR(100) COMMENT 'ORIGINRESULT',
	ACTUALOPENTIME VARCHAR(100) COMMENT 'ACTUALOPENTIME',
	ACTUALCLOSETIME VARCHAR(100) COMMENT 'ACTUALCLOSETIME',
	PRIMARY KEY (ROUNDID)
) COMMENT = 'lottery_round';


CREATE TABLE LOTTERY_ROUND_ITEM
(
	-- 游戏ID
	ROUNDID INT NOT NULL COMMENT 'RoundId',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT 'ItemNo',
	-- 游戏界面显示的赔率
	ITEMSCALE DOUBLE(18,4) COMMENT 'ItemScale',
	-- 派彩赔率
	ITEMODDS DOUBLE(18,4) COMMENT 'ItemOdds',
	-- 抽水比例
	ITEMBONUS DOUBLE(18,4) COMMENT 'ItemBonus',
	-- 更新时间
	UPDATETIME DATETIME COMMENT 'updateTime',
	PRIMARY KEY (ROUNDID, ITEMNO),
	UNIQUE (ROUNDID, ITEMNO)
) COMMENT = 'lottery_round_item';


CREATE TABLE LOTTERY_ROUND_ITEM
(
	-- 游戏ID
	ROUNDID INT NOT NULL COMMENT '游戏ID',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT '投注项编号',
	-- 游戏界面显示的赔率
	ITEMSCALE DOUBLE(18,4) COMMENT '游戏界面显示的赔率',
	-- 更新时间
	UPDATETIME DATETIME COMMENT '更新时间',
	PRIMARY KEY (ROUNDID, ITEMNO)
) COMMENT = 'lottery_round_item';


CREATE TABLE LOTTERY_SERVICE
(
	SID INT(11) NOT NULL UNIQUE COMMENT 'sid',
	LOGINSERVICE VARCHAR(4) COMMENT 'loginservice',
	REGISTERSERCICE VARCHAR(4) COMMENT 'registersercice',
	ADDEDSERVICE VARCHAR(4) COMMENT 'addedservice',
	PLAYSERVICE VARCHAR(4) COMMENT 'playservice',
	AREMARKSERCIE VARCHAR(200) COMMENT 'aremarksercie',
	DREMARKSERCIE VARCHAR(200) COMMENT 'dremarksercie',
	PRIMARY KEY (SID)
) COMMENT = 'lottery_service';


CREATE TABLE NOTICE_INFO
(
	-- 公告ID
	NOTICEID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'NoticeId',
	-- 公告内容
	NOTICECONTENT VARCHAR(500) NOT NULL COMMENT 'NoticeContent',
	-- 是否有效
	ISVALID BOOLEAN DEFAULT '1' NOT NULL COMMENT 'IsValid',
	PRIMARY KEY (NOTICEID)
) COMMENT = 'notice_info';


CREATE TABLE NOTICE_INFO
(
	NOTICEID INT NOT NULL AUTO_INCREMENT COMMENT 'Noticeid',
	TITLE VARCHAR(200) COMMENT 'Title',
	NOTICE VARCHAR(2000) COMMENT 'Notice',
	STYPE CHAR(1) COMMENT 'Stype',
	UPDATEIP VARCHAR(20) COMMENT 'UpdateIP',
	UPDATEDATE DATETIME COMMENT 'UpdateDate',
	STATE CHAR(1) COMMENT 'State',
	SUPUSERNAME VARCHAR(20) COMMENT 'SupUserName',
	OFFTYPE CHAR(1) COMMENT 'OffType',
	ATTRIBUTE1 VARCHAR(20) COMMENT 'Attribute1',
	ATTRIBUTE2 VARCHAR(20) COMMENT 'Attribute2',
	PRIMARY KEY (NOTICEID)
) COMMENT = 'notice_info';


CREATE TABLE OFFACCOUNT_INFO
(
	ACCOUNTID INT NOT NULL AUTO_INCREMENT COMMENT '用户流水号',
	USERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL COMMENT '用户名',
	AUSERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL COMMENT '别名（昵称）',
	PASSWORD VARCHAR(50) DEFAULT '<EMPTY STRING>' NOT NULL COMMENT '密码',
	LIMITED DOUBLE(18,2) DEFAULT 0.00 COMMENT 'Limited',
	RATIO DOUBLE(18,4) DEFAULT 0.00 COMMENT '洗码比',
	PERCENTAGE DOUBLE(18,4) DEFAULT 0.00 COMMENT 'Percentage',
	QUERY VARCHAR(50) DEFAULT '<EMPTY STRING>' COMMENT 'Query',
	MANAGE VARCHAR(50) DEFAULT '<EMPTY STRING>' COMMENT 'Manage',
	IP VARCHAR(20) DEFAULT '<EMPTY STRING>' COMMENT 'IP地址',
	INPUTDATE DATETIME COMMENT '新增时间',
	UPDATEIP VARCHAR(20) DEFAULT '<EMPTY STRING>' COMMENT '修改IP',
	UPDATEDATE DATETIME COMMENT '修改时间',
	STATE CHAR DEFAULT '1' COMMENT '状态',
	SUPUSERID VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL COMMENT '上级编号',
	LEVEL VARCHAR(20) DEFAULT '<EMPTY STRING>' COMMENT '级别',
	OFFTYPE CHAR DEFAULT '<EMPTY STRING>' COMMENT 'OffType',
	-- 风险限额
	RISKAMOUNT VARCHAR(100) COMMENT 'RiskAmount',
	ATTRIBUTE2 VARCHAR(20) COMMENT 'Attribute2',
	PRIMARY KEY (ACCOUNTID)
) COMMENT = 'offaccount_info' DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE OFFACCOUNT_INFO
(
	USERID INT NOT NULL AUTO_INCREMENT COMMENT 'USERID',
	USERNAME VARCHAR(20) NOT NULL COMMENT 'USERNAME',
	AUSERNAME VARCHAR(20) NOT NULL COMMENT 'AUSERNAME',
	PASSWORD VARCHAR(50) NOT NULL COMMENT 'PASSWORD',
	LIMITED DOUBLE(18,2) DEFAULT 0.00 COMMENT 'LIMITED',
	RATIO DOUBLE(18,4) DEFAULT 0.0000 COMMENT 'RATIO',
	PERCENTAGE DOUBLE(18,4) DEFAULT 0.0000 COMMENT 'PERCENTAGE',
	QUERY VARCHAR(50) COMMENT 'QUERY',
	MANAGE VARCHAR(50) COMMENT 'MANAGE',
	IP VARCHAR(20) COMMENT 'IP',
	INPUTDATE DATETIME COMMENT 'INPUTDATE',
	UPDATEIP VARCHAR(20) COMMENT 'UPDATEIP',
	UPDATEDATE DATETIME COMMENT 'UPDATEDATE',
	STATE CHAR(1) DEFAULT '1' COMMENT 'STATE',
	SUPUSERNAME VARCHAR(20) NOT NULL COMMENT 'SUPUSERNAME',
	LEVEL VARCHAR(20) COMMENT 'LEVEL',
	OFFTYPE CHAR(1) COMMENT 'OFFTYPE',
	RISKAMOUNT VARCHAR(100) COMMENT 'RISKAMOUNT',
	ATTRIBUTE2 VARCHAR(20) COMMENT 'ATTRIBUTE2',
	PRIMARY KEY (USERID)
) COMMENT = 'offaccount_info';


CREATE TABLE SUBACCOUNT_INFO
(
	SERIALNO INT NOT NULL AUTO_INCREMENT COMMENT 'Serialno',
	USERNAME VARCHAR(20) NOT NULL COMMENT 'UserName',
	AUSERNAME VARCHAR(20) NOT NULL COMMENT 'AuserName',
	PASSWORD VARCHAR(50) NOT NULL COMMENT 'Password',
	QUERY VARCHAR(20) COMMENT 'Query',
	MANAGE VARCHAR(20) COMMENT 'Manage',
	IP VARCHAR(20) COMMENT 'IP',
	INPUTDATE DATETIME COMMENT 'InputDate',
	UPDATEIP VARCHAR(20) COMMENT 'UpdateIP',
	UPDATEDATE DATETIME COMMENT 'UpdateDate',
	STATE CHAR(1) NOT NULL COMMENT 'State',
	SUPUSERNAME VARCHAR(20) COMMENT 'SupUserName',
	LEVEL VARCHAR(20) COMMENT 'Level',
	ATTRIBUTE1 VARCHAR(20) COMMENT 'Attribute1',
	ATTRIBUTE2 VARCHAR(20) COMMENT 'Attribute2',
	PRIMARY KEY (SERIALNO)
) COMMENT = 'subaccount_info';


CREATE TABLE TASK_SCHEDULE_JOB
(
	JOB_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'job_id',
	CREATE_TIME TIMESTAMP COMMENT 'create_time',
	UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'update_time',
	JOB_NAME VARCHAR(255) COMMENT 'job_name',
	JOB_GROUP VARCHAR(255) COMMENT 'job_group',
	JOB_STATUS VARCHAR(255) COMMENT 'job_status',
	CRON_EXPRESSION VARCHAR(255) NOT NULL COMMENT 'cron_expression',
	DESCRIPTION VARCHAR(255) COMMENT 'description',
	BEAN_CLASS VARCHAR(255) COMMENT 'bean_class',
	-- 1
	IS_CONCURRENT VARCHAR(255) COMMENT '1',
	SPRING_ID VARCHAR(255) COMMENT 'spring_id',
	METHOD_NAME VARCHAR(255) NOT NULL COMMENT 'method_name',
	PRIMARY KEY (JOB_ID)
) COMMENT = 'task_schedule_job';


CREATE TABLE TRADE_INFO
(
	-- 流水号
	TRADEID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'TradeId',
	-- 账户ID
	USERID INT NOT NULL COMMENT 'userid',
	-- 业务类型：Inout出入金；Trade交易；
	TRADETYPE VARCHAR(10) NOT NULL COMMENT 'TradeType',
	RELATIVEID INT COMMENT 'RelativeId',
	-- 业务关联类型:In入金；Out出金；Commision提成；Pay付款；Order投注；Prize奖金；Return洗码
	RELATIVETYPE VARCHAR(10) NOT NULL COMMENT 'RelativeType',
	-- 交易金额
	TRADEAMOUNT DOUBLE(18,2) NOT NULL COMMENT 'TradeAmount',
	-- 帐号余额
	ACCOUNTAMOUNT DECIMAL(19,2) COMMENT 'AccountAmount',
	-- 录入时间
	INPUTTIME DATETIME COMMENT 'InputTime',
	REMARK VARCHAR(100) COMMENT 'Remark',
	PRIMARY KEY (TRADEID)
) COMMENT = 'trade_info';


CREATE TABLE TRADE_INFO
(
	-- 流水号
	TRADEID INT NOT NULL AUTO_INCREMENT COMMENT '流水号',
	-- 帐户ID
	ACCOUNTID INT NOT NULL COMMENT '帐户ID',
	-- 业务类型：Inout出入金；Trade交易；
	TRADETYPE VARCHAR(10) NOT NULL COMMENT '业务类型：Inout出入金；Trade交易；',
	RELATIVEID INT COMMENT 'RELATIVEID',
	-- 业务关联类型:In入金；Out出金；Commision提成；Pay付款；Order投注；Prize奖金；Return洗码
	RELATIVETYPE VARCHAR(10) NOT NULL COMMENT '业务关联类型:In入金；Out出金；Commision提成；Pay付款；Order投注；Prize奖金；Return洗码',
	-- 交易金额
	TRADEAMOUNT DOUBLE(18,2) NOT NULL COMMENT '交易金额',
	-- 帐号余额
	ACCOUNTAMOUNT DECIMAL(19,2) COMMENT '帐号余额',
	-- 录入时间
	INPUTTIME DATETIME COMMENT '录入时间',
	REMARK VARCHAR(100) COMMENT 'REMARK',
	PRIMARY KEY (TRADEID)
) COMMENT = 'trade_info';


CREATE TABLE T_S_TIMETASK
(
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	CREATE_BY VARCHAR(32) COMMENT 'CREATE_BY',
	CREATE_DATE DATETIME COMMENT 'CREATE_DATE',
	CREATE_NAME VARCHAR(32) COMMENT 'CREATE_NAME',
	CRON_EXPRESSION VARCHAR(100) NOT NULL COMMENT 'CRON_EXPRESSION',
	IS_EFFECT VARCHAR(1) NOT NULL COMMENT 'IS_EFFECT',
	IS_START VARCHAR(1) NOT NULL COMMENT 'IS_START',
	TASK_DESCRIBE VARCHAR(50) NOT NULL COMMENT 'TASK_DESCRIBE',
	TASK_ID VARCHAR(100) NOT NULL COMMENT 'TASK_ID',
	START_TIME DATETIME COMMENT 'START_TIME',
	UPDATE_BY VARCHAR(32) COMMENT 'UPDATE_BY',
	UPDATE_DATE DATETIME COMMENT 'UPDATE_DATE',
	UPDATE_NAME VARCHAR(32) COMMENT 'UPDATE_NAME',
	PRIMARY KEY (ID)
) COMMENT = 't_s_timetask';



/* Create Foreign Keys */

ALTER TABLE LOTTERY_ORDER
	ADD FOREIGN KEY (ACCOUNTID)
	REFERENCES ACCOUNT_DETAIL (ACCOUNTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRADE_INFO
	ADD FOREIGN KEY (USERID)
	REFERENCES ACCOUNT_DETAIL (ACCOUNTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOTTERY_ORDER
	ADD CONSTRAINT LOTTERY_ORDER_IBFK_1 FOREIGN KEY (ACCOUNTID)
	REFERENCES ACCOUNT_DETAIL (ACCOUNTID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE TRADE_INFO
	ADD CONSTRAINT TRADE_INFO_IBFK_1 FOREIGN KEY (ACCOUNTID)
	REFERENCES ACCOUNT_DETAIL (ACCOUNTID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE LOTTERY_ORDER_DETAIL
	ADD FOREIGN KEY (ORDERID)
	REFERENCES LOTTERY_ORDER (ORDERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOTTERY_ORDER_DETAIL
	ADD CONSTRAINT LOTTERY_ORDER_DETAIL_IBFK_1 FOREIGN KEY (ORDERID)
	REFERENCES LOTTERY_ORDER (ORDERID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE LOTTERY_ORDER
	ADD FOREIGN KEY (ROUNDID)
	REFERENCES LOTTERY_ROUND (ROUNDID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOTTERY_ROUND_ITEM
	ADD FOREIGN KEY (ROUNDID)
	REFERENCES LOTTERY_ROUND (ROUNDID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOTTERY_ORDER
	ADD CONSTRAINT LOTTERY_ORDER_IBFK_2 FOREIGN KEY (ROUNDID)
	REFERENCES LOTTERY_ROUND (ROUNDID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE LOTTERY_ROUND_ITEM
	ADD CONSTRAINT LOTTERY_ROUND_ITEM_IBFK_1 FOREIGN KEY (ROUNDID)
	REFERENCES LOTTERY_ROUND (ROUNDID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;



/* Create Indexes */

CREATE INDEX ACCOUNTID USING BTREE ON LOTTERY_ORDER (ACCOUNTID ASC);
CREATE INDEX ROUNDID USING BTREE ON LOTTERY_ORDER (ROUNDID ASC);
CREATE UNIQUE INDEX ORDERID USING BTREE ON LOTTERY_ORDER_DETAIL (ORDERID ASC, ITEMNO ASC);
CREATE UNIQUE INDEX LOTTERYTYPE USING BTREE ON LOTTERY_ROUND (LOTTERYTYPE ASC, LOTTERYTERM ASC);
CREATE UNIQUE INDEX ROUNDID USING BTREE ON LOTTERY_ROUND_ITEM (ROUNDID ASC, ITEMNO ASC);
CREATE UNIQUE INDEX NAME_GROUP USING BTREE ON TASK_SCHEDULE_JOB (JOB_NAME ASC, JOB_GROUP ASC);
CREATE INDEX ACCOUNTID USING BTREE ON TRADE_INFO (ACCOUNTID ASC);



