SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Indexes */

DROP INDEX ACCOUNTID ON LOTTERY_ORDER;
DROP INDEX ROUNDID ON LOTTERY_ORDER;
DROP INDEX ORDERID ON LOTTERY_ORDER_DETAIL;
DROP INDEX LOTTERYTYPE ON LOTTERY_ROUND;
DROP INDEX ROUNDID ON LOTTERY_ROUND_ITEM;
DROP INDEX NAME_GROUP ON TASK_SCHEDULE_JOB;
DROP INDEX ACCOUNTID ON TRADE_INFO;



/* Drop Tables */

DROP TABLE LOTTERY_ORDER_DETAIL;
DROP TABLE LOTTERY_ORDER;
DROP TABLE TRADE_INFO;
DROP TABLE ACCOUNT_DETAIL;
DROP TABLE LOTTERY_ORDER_DETAIL;
DROP TABLE LOTTERY_ORDER;
DROP TABLE TRADE_INFO;
DROP TABLE ACCOUNT_DETAIL;
DROP TABLE ACCOUNT_INFO;
DROP TABLE ACCOUNT_INFO;
DROP TABLE ACCOUNT_INFO;
DROP TABLE ACCOUNT_INFO;
DROP TABLE LOTTERY_ITEM;
DROP TABLE LOTTERY_ITEM;
DROP TABLE LOTTERY_ROUND_ITEM;
DROP TABLE LOTTERY_ROUND;
DROP TABLE LOTTERY_ROUND_ITEM;
DROP TABLE LOTTERY_ROUND;
DROP TABLE LOTTERY_SERVICE;
DROP TABLE NOTICE_INFO;
DROP TABLE NOTICE_INFO;
DROP TABLE OFFACCOUNT_INFO;
DROP TABLE OFFACCOUNT_INFO;
DROP TABLE SUBACCOUNT_INFO;
DROP TABLE TASK_SCHEDULE_JOB;
DROP TABLE T_S_TIMETASK;




/* Create Tables */

CREATE TABLE ACCOUNT_DETAIL
(
	ACCOUNTID INT NOT NULL AUTO_INCREMENT,
	USERID INT NOT NULL,
	USERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL,
	LIMITED DOUBLE(18,2) DEFAULT 0.00,
	RATIO DOUBLE(18,4) DEFAULT 0.00,
	PERCENTAGE DOUBLE(18,4) DEFAULT 0.00,
	STATE CHAR DEFAULT '1',
	SUPUSERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>',
	LEVEL VARCHAR(20) DEFAULT '<EMPTY STRING>',
	OFFTYPE CHAR,
	ATTRIBUTE1 VARCHAR(20),
	MONEY DECIMAL(19,2) DEFAULT 0.00,
	ATTRIBUTE2 VARCHAR(20),
	PRIMARY KEY (ACCOUNTID),
	UNIQUE (USERNAME)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE ACCOUNT_DETAIL
(
	ACCOUNTID INT NOT NULL AUTO_INCREMENT,
	USERID INT NOT NULL,
	USERNAME VARCHAR(20) NOT NULL UNIQUE,
	LIMITED DOUBLE(18,2) DEFAULT 0.00,
	RATIO DOUBLE(18,4) DEFAULT 0.0000,
	PERCENTAGE DOUBLE(18,4) DEFAULT 0.0000,
	STATE CHAR(1) DEFAULT '1',
	SUPUSERNAME VARCHAR(20),
	LEVEL VARCHAR(20),
	OFFTYPE CHAR(1),
	MONEY DECIMAL(19,2) DEFAULT 0.00,
	ATTRIBUTE1 VARCHAR(20),
	ATTRIBUTE2 VARCHAR(20),
	BUDGET VARCHAR(100),
	PRIMARY KEY (ACCOUNTID)
);


CREATE TABLE ACCOUNT_INFO
(
	USERID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	AUSERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	LIMITED DOUBLE(18,2) DEFAULT 0.00,
	RATIO DOUBLE(18,4) DEFAULT 0.0000,
	IP VARCHAR(20),
	INPUTDATE DATETIME,
	UPDATEIP VARCHAR(20),
	UPDATEDATE DATETIME,
	STATE CHAR(1) NOT NULL,
	SUPUSERNAME VARCHAR(20) NOT NULL,
	LEVEL VARCHAR(20),
	PHONE VARCHAR(20),
	WEBCHAT VARCHAR(30),
	PRIMARY KEY (USERID)
);


CREATE TABLE ACCOUNT_INFO
(
	USERID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	AUSERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	LIMITED DOUBLE(18,2) DEFAULT 0.00,
	RATIO DOUBLE(18,4) DEFAULT 0.0000,
	IP VARCHAR(20),
	INPUTDATE DATETIME,
	UPDATEIP VARCHAR(20),
	UPDATEDATE DATETIME,
	STATE CHAR(1) NOT NULL,
	SUPUSERNAME VARCHAR(20) NOT NULL,
	LEVEL VARCHAR(20),
	PHONE VARCHAR(20),
	WEBCHAT VARCHAR(30),
	PRIMARY KEY (USERID)
);


CREATE TABLE ACCOUNT_INFO
(
	USERID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	AUSERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	LIMITED DOUBLE(18,2) DEFAULT 0.00,
	RATIO DOUBLE(18,4) DEFAULT 0.0000,
	IP VARCHAR(20),
	INPUTDATE DATETIME,
	UPDATEIP VARCHAR(20),
	UPDATEDATE DATETIME,
	STATE CHAR(1) NOT NULL,
	SUPUSERNAME VARCHAR(20) NOT NULL,
	LEVEL VARCHAR(20),
	PHONE VARCHAR(20),
	WEBCHAT VARCHAR(30),
	PRIMARY KEY (USERID)
);


CREATE TABLE ACCOUNT_INFO
(
	USERID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL,
	AUSERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL,
	PASSWORD VARCHAR(50) DEFAULT '<EMPTY STRING>' NOT NULL,
	LIMITED DOUBLE(18,2) DEFAULT 0.00,
	RATIO DOUBLE(18,4) DEFAULT 0.00,
	IP VARCHAR(20) DEFAULT '<EMPTY STRING>',
	INPUTDATE DATETIME,
	UPDATEIP VARCHAR(20) DEFAULT '<EMPTY STRING>',
	UPDATEDATE DATETIME,
	STATE CHAR NOT NULL,
	SUPUSERID VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL,
	LEVEL VARCHAR(20) DEFAULT '<EMPTY STRING>',
	PHONE VARCHAR(20),
	WEBCHAT VARCHAR(30),
	USERMONEY DECIMAL(19,2),
	OFFTYPE VARCHAR(10),
	PERCENTAGE DOUBLE(18,4),
	QUERY VARCHAR(100),
	BUDGET VARCHAR(100),
	CODE VARCHAR(6),
	SFCODE VARCHAR(30),
	BANKID VARCHAR(100),
	BANKNAME VARCHAR(100),
	BANKADDRESS VARCHAR(100),
	BANKACCOUNT VARCHAR(100),
	PRIMARY KEY (USERID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE LOTTERY_ITEM
(
	-- 流水号
	ITEMID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '流水号',
	-- 游戏类型：01玉米籽
	LOTTERYTYPE VARCHAR(10) NOT NULL COMMENT '游戏类型：01玉米籽',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT '投注项编号',
	-- 投注项名称
	ITEMNAME VARCHAR(50) COMMENT '投注项名称',
	-- 投注项类型：01广西快乐十分，02番摊玉米籽
	ITEMTYPE VARCHAR(10) COMMENT '投注项类型：01广西快乐十分，02番摊玉米籽',
	-- 类别，如特码、色、单双、大小等
	ITEMGROUP VARCHAR(20) COMMENT '类别，如特码、色、单双、大小等',
	-- 游戏界面显示的赔率
	ITEMSCALE DOUBLE(18,4) NOT NULL COMMENT '游戏界面显示的赔率',
	-- 派彩赔率
	ITEMODDS DOUBLE(18,4) COMMENT '派彩赔率',
	-- 抽水比例
	ITEMBONUS DOUBLE(18,4) COMMENT '抽水比例',
	-- 下注项中文名称
	ITEMNAMECN VARCHAR(50) COMMENT '下注项中文名称',
	PRIMARY KEY (ITEMID)
);


CREATE TABLE LOTTERY_ITEM
(
	-- 流水号
	ITEMID INT NOT NULL AUTO_INCREMENT COMMENT '流水号',
	-- 游戏类型：01玉米籽
	LOTTERYTYPE VARCHAR(10) NOT NULL COMMENT '游戏类型：01玉米籽',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT '投注项编号',
	-- 投注项名称
	ITEMNAME VARCHAR(50) COMMENT '投注项名称',
	-- 投注项类型：01广西快乐十分，02番摊玉米籽
	ITEMTYPE VARCHAR(10) COMMENT '投注项类型：01广西快乐十分，02番摊玉米籽',
	-- 类别，如特码、色、单双、大小等
	ITEMGROUP VARCHAR(20) COMMENT '类别，如特码、色、单双、大小等',
	-- 游戏界面显示的赔率
	ITEMSCALE DOUBLE(18,4) NOT NULL COMMENT '游戏界面显示的赔率',
	-- 派彩赔率
	ITEMODDS DOUBLE(18,4) COMMENT '派彩赔率',
	-- 抽水比例
	ITEMBONUS DOUBLE(18,4) COMMENT '抽水比例',
	PRIMARY KEY (ITEMID)
);


CREATE TABLE LOTTERY_ORDER
(
	-- 投注单ID
	ORDERID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '投注单ID',
	-- 游戏ID
	ROUNDID INT NOT NULL COMMENT '游戏ID',
	-- 账户ID
	ACCOUNTID INT NOT NULL COMMENT '账户ID',
	-- 投注金额
	ORDERAMOUNT DOUBLE(18,2) COMMENT '投注金额',
	-- 代理提成
	COMMISIONAMOUNT DOUBLE(18,2) COMMENT '代理提成',
	ORDERTIME DATETIME NOT NULL,
	-- 中奖金额
	PRIZEAMOUNT DOUBLE(18,2) COMMENT '中奖金额',
	-- 实际到手奖金
	ACTUALAMOUNT DOUBLE(18,2) COMMENT '实际到手奖金',
	-- 抽水返利
	RETURNAMOUNT DOUBLE(18,2) COMMENT '抽水返利',
	-- 中奖时间
	PRIZETIME DATETIME COMMENT '中奖时间',
	-- 帐号余额
	ACCOUNTAMOUNT DECIMAL(19,2) COMMENT '帐号余额',
	PRIMARY KEY (ORDERID)
);


CREATE TABLE LOTTERY_ORDER
(
	-- 投注单ID
	ORDERID INT NOT NULL AUTO_INCREMENT COMMENT '投注单ID',
	-- 游戏ID
	ROUNDID INT NOT NULL COMMENT '游戏ID',
	-- 帐户ID
	ACCOUNTID INT NOT NULL COMMENT '帐户ID',
	-- 投注金额
	ORDERAMOUNT DOUBLE(18,2) COMMENT '投注金额',
	-- 代理提成
	COMMISIONAMOUNT DOUBLE(18,2) COMMENT '代理提成',
	ORDERTIME DATETIME NOT NULL,
	-- 中奖金额
	PRIZEAMOUNT DOUBLE(18,2) COMMENT '中奖金额',
	-- 实际到手奖金
	ACTUALAMOUNT DOUBLE(18,2) COMMENT '实际到手奖金',
	-- 抽水返利
	RETURNAMOUNT DOUBLE(18,2) COMMENT '抽水返利',
	SYSTEMAMOUNT DOUBLE(18,2),
	-- 中奖时间
	PRIZETIME DATETIME COMMENT '中奖时间',
	-- 帐号余额
	ACCOUNTAMOUNT DECIMAL(19,2) COMMENT '帐号余额',
	PRIMARY KEY (ORDERID)
);


CREATE TABLE LOTTERY_ORDER_DETAIL
(
	-- 投注单ID
	ORDERID INT NOT NULL COMMENT '投注单ID',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT '投注项编号',
	-- 赔率
	ITEMSCALE DOUBLE(18,4) COMMENT '赔率',
	-- 抽水比例
	ITEMBONUS DOUBLE(18,4) COMMENT '抽水比例',
	-- 投注金额
	DETAILAMOUNT DOUBLE(18,2) COMMENT '投注金额',
	-- 中奖金额
	PRIZEAMOUNT DOUBLE(18,2) COMMENT '中奖金额',
	-- 实际到手奖金
	ACTUALAMOUNT DOUBLE(18,2) COMMENT '实际到手奖金',
	-- 抽水返利
	RETURNAMOUNT DOUBLE(18,2) COMMENT '抽水返利',
	PRIMARY KEY (ORDERID, ITEMNO)
);


CREATE TABLE LOTTERY_ORDER_DETAIL
(
	-- 投注单ID
	ORDERID INT NOT NULL COMMENT '投注单ID',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT '投注项编号',
	-- 派彩赔率
	ITEMODDS DOUBLE(18,4) COMMENT '派彩赔率',
	-- 抽水比例
	ITEMBONUS DOUBLE(18,4) COMMENT '抽水比例',
	-- 投注金额
	DETAILAMOUNT DOUBLE(18,2) COMMENT '投注金额',
	-- 中奖金额
	PRIZEAMOUNT DOUBLE(18,2) COMMENT '中奖金额',
	-- 实际到手奖金
	ACTUALAMOUNT DOUBLE(18,2) COMMENT '实际到手奖金',
	-- 抽水返利
	RETURNAMOUNT DOUBLE(18,2) COMMENT '抽水返利',
	PRIMARY KEY (ORDERID, ITEMNO),
	UNIQUE (ORDERID, ITEMNO)
);


CREATE TABLE LOTTERY_ROUND
(
	-- 游戏ID
	ROUNDID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '游戏ID',
	-- 游戏类型：01玉米籽
	LOTTERYTYPE VARCHAR(10) NOT NULL COMMENT '游戏类型：01玉米籽',
	-- 期次
	LOTTERYTERM VARCHAR(20) NOT NULL COMMENT '期次',
	-- 开出之号码
	RESULTSTR VARCHAR(100) COMMENT '开出之号码',
	-- 游戏开始时间
	STARTTIME DATETIME COMMENT '游戏开始时间',
	-- 游戏开奖时间
	ENDTIME DATETIME COMMENT '游戏开奖时间',
	-- 游戏状态：Open开盘中，Close已封盘，End已结束
	ROUNDSTATUS VARCHAR(10) NOT NULL COMMENT '游戏状态：Open开盘中，Close已封盘，End已结束',
	-- 开奖时间
	OPENTIME DATETIME COMMENT '开奖时间',
	-- 封盘时间
	CLOSETIME DATETIME COMMENT '封盘时间',
	-- 广西快乐十分开奖结果
	ORIGINRESULT VARCHAR(100) COMMENT '广西快乐十分开奖结果',
	PRIMARY KEY (ROUNDID),
	UNIQUE (LOTTERYTYPE, LOTTERYTERM)
);


CREATE TABLE LOTTERY_ROUND
(
	-- 游戏ID
	ROUNDID INT NOT NULL AUTO_INCREMENT COMMENT '游戏ID',
	-- 游戏类型：01玉米籽
	LOTTERYTYPE VARCHAR(10) NOT NULL COMMENT '游戏类型：01玉米籽',
	-- 期次
	LOTTERYTERM VARCHAR(20) NOT NULL COMMENT '期次',
	-- 开出之号码
	RESULTSTR VARCHAR(100) COMMENT '开出之号码',
	-- 游戏开始时间
	STARTTIME DATETIME COMMENT '游戏开始时间',
	-- 游戏开奖时间
	ENDTIME DATETIME COMMENT '游戏开奖时间',
	-- 游戏状态：Open开盘中，Close已封盘，End已结束
	ROUNDSTATUS VARCHAR(10) NOT NULL COMMENT '游戏状态：Open开盘中，Close已封盘，End已结束',
	OPENTIME DATETIME,
	CLOSETIME DATETIME,
	ORIGINRESULT VARCHAR(100),
	ACTUALOPENTIME VARCHAR(100),
	ACTUALCLOSETIME VARCHAR(100),
	PRIMARY KEY (ROUNDID)
);


CREATE TABLE LOTTERY_ROUND_ITEM
(
	-- 游戏ID
	ROUNDID INT NOT NULL COMMENT '游戏ID',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT '投注项编号',
	-- 游戏界面显示的赔率
	ITEMSCALE DOUBLE(18,4) COMMENT '游戏界面显示的赔率',
	-- 派彩赔率
	ITEMODDS DOUBLE(18,4) COMMENT '派彩赔率',
	-- 抽水比例
	ITEMBONUS DOUBLE(18,4) COMMENT '抽水比例',
	-- 更新时间
	UPDATETIME DATETIME COMMENT '更新时间',
	PRIMARY KEY (ROUNDID, ITEMNO),
	UNIQUE (ROUNDID, ITEMNO)
);


CREATE TABLE LOTTERY_ROUND_ITEM
(
	-- 游戏ID
	ROUNDID INT NOT NULL COMMENT '游戏ID',
	-- 投注项编号
	ITEMNO VARCHAR(10) NOT NULL COMMENT '投注项编号',
	-- 游戏界面显示的赔率
	ITEMSCALE DOUBLE(18,4) COMMENT '游戏界面显示的赔率',
	-- 更新时间
	UPDATETIME DATETIME COMMENT '更新时间',
	PRIMARY KEY (ROUNDID, ITEMNO)
);


CREATE TABLE LOTTERY_SERVICE
(
	SID INT(11) NOT NULL UNIQUE,
	LOGINSERVICE VARCHAR(4),
	REGISTERSERCICE VARCHAR(4),
	ADDEDSERVICE VARCHAR(4),
	PLAYSERVICE VARCHAR(4),
	AREMARKSERCIE VARCHAR(200),
	DREMARKSERCIE VARCHAR(200),
	PRIMARY KEY (SID)
);


CREATE TABLE NOTICE_INFO
(
	-- 公告ID
	NOTICEID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '公告ID',
	-- 公告内容
	NOTICECONTENT VARCHAR(500) NOT NULL COMMENT '公告内容',
	-- 是否有效
	ISVALID BOOLEAN DEFAULT '1' NOT NULL COMMENT '是否有效',
	PRIMARY KEY (NOTICEID)
);


CREATE TABLE NOTICE_INFO
(
	NOTICEID INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(200),
	NOTICE VARCHAR(2000),
	STYPE CHAR(1),
	UPDATEIP VARCHAR(20),
	UPDATEDATE DATETIME,
	STATE CHAR(1),
	SUPUSERNAME VARCHAR(20),
	OFFTYPE CHAR(1),
	ATTRIBUTE1 VARCHAR(20),
	ATTRIBUTE2 VARCHAR(20),
	PRIMARY KEY (NOTICEID)
);


CREATE TABLE OFFACCOUNT_INFO
(
	USERID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL,
	AUSERNAME VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL,
	PASSWORD VARCHAR(50) DEFAULT '<EMPTY STRING>' NOT NULL,
	LIMITED DOUBLE(18,2) DEFAULT 0.00,
	RATIO DOUBLE(18,4) DEFAULT 0.00,
	PERCENTAGE DOUBLE(18,4) DEFAULT 0.00,
	QUERY VARCHAR(50) DEFAULT '<EMPTY STRING>',
	MANAGE VARCHAR(50) DEFAULT '<EMPTY STRING>',
	IP VARCHAR(20) DEFAULT '<EMPTY STRING>',
	INPUTDATE DATETIME,
	UPDATEIP VARCHAR(20) DEFAULT '<EMPTY STRING>',
	UPDATEDATE DATETIME,
	STATE CHAR DEFAULT '1',
	SUPUSERID VARCHAR(20) DEFAULT '<EMPTY STRING>' NOT NULL,
	LEVEL VARCHAR(20) DEFAULT '<EMPTY STRING>',
	OFFTYPE CHAR DEFAULT '<EMPTY STRING>',
	-- 风险限额
	RISKAMOUNT VARCHAR(100) COMMENT '风险限额',
	ATTRIBUTE2 VARCHAR(20),
	PRIMARY KEY (USERID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE OFFACCOUNT_INFO
(
	USERID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	AUSERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	LIMITED DOUBLE(18,2) DEFAULT 0.00,
	RATIO DOUBLE(18,4) DEFAULT 0.0000,
	PERCENTAGE DOUBLE(18,4) DEFAULT 0.0000,
	QUERY VARCHAR(50),
	MANAGE VARCHAR(50),
	IP VARCHAR(20),
	INPUTDATE DATETIME,
	UPDATEIP VARCHAR(20),
	UPDATEDATE DATETIME,
	STATE CHAR(1) DEFAULT '1',
	SUPUSERNAME VARCHAR(20) NOT NULL,
	LEVEL VARCHAR(20),
	OFFTYPE CHAR(1),
	RISKAMOUNT VARCHAR(100),
	ATTRIBUTE2 VARCHAR(20),
	PRIMARY KEY (USERID)
);


CREATE TABLE SUBACCOUNT_INFO
(
	SERIALNO INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	AUSERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	QUERY VARCHAR(20),
	MANAGE VARCHAR(20),
	IP VARCHAR(20),
	INPUTDATE DATETIME,
	UPDATEIP VARCHAR(20),
	UPDATEDATE DATETIME,
	STATE CHAR(1) NOT NULL,
	SUPUSERNAME VARCHAR(20),
	LEVEL VARCHAR(20),
	ATTRIBUTE1 VARCHAR(20),
	ATTRIBUTE2 VARCHAR(20),
	PRIMARY KEY (SERIALNO)
);


CREATE TABLE TASK_SCHEDULE_JOB
(
	JOB_ID BIGINT NOT NULL AUTO_INCREMENT,
	CREATE_TIME TIMESTAMP,
	UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	JOB_NAME VARCHAR(255),
	JOB_GROUP VARCHAR(255),
	JOB_STATUS VARCHAR(255),
	CRON_EXPRESSION VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255),
	BEAN_CLASS VARCHAR(255),
	-- 1
	IS_CONCURRENT VARCHAR(255) COMMENT '1',
	SPRING_ID VARCHAR(255),
	METHOD_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (JOB_ID)
);


CREATE TABLE TRADE_INFO
(
	-- 流水号
	TRADEID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '流水号',
	-- 账户ID
	ACCOUNTID INT NOT NULL COMMENT '账户ID',
	-- 业务类型：Inout出入金；Trade交易；
	TRADETYPE VARCHAR(10) NOT NULL COMMENT '业务类型：Inout出入金；Trade交易；',
	RELATIVEID INT,
	-- 业务关联类型:In入金；Out出金；Commision提成；Pay付款；Order投注；Prize奖金；Return洗码
	RELATIVETYPE VARCHAR(10) NOT NULL COMMENT '业务关联类型:In入金；Out出金；Commision提成；Pay付款；Order投注；Prize奖金；Return洗码',
	-- 交易金额
	TRADEAMOUNT DOUBLE(18,2) NOT NULL COMMENT '交易金额',
	-- 帐号余额
	ACCOUNTAMOUNT DECIMAL(19,2) COMMENT '帐号余额',
	-- 录入时间
	INPUTTIME DATETIME COMMENT '录入时间',
	REMARK VARCHAR(100),
	PRIMARY KEY (TRADEID)
);


CREATE TABLE TRADE_INFO
(
	-- 流水号
	TRADEID INT NOT NULL AUTO_INCREMENT COMMENT '流水号',
	-- 帐户ID
	ACCOUNTID INT NOT NULL COMMENT '帐户ID',
	-- 业务类型：Inout出入金；Trade交易；
	TRADETYPE VARCHAR(10) NOT NULL COMMENT '业务类型：Inout出入金；Trade交易；',
	RELATIVEID INT,
	-- 业务关联类型:In入金；Out出金；Commision提成；Pay付款；Order投注；Prize奖金；Return洗码
	RELATIVETYPE VARCHAR(10) NOT NULL COMMENT '业务关联类型:In入金；Out出金；Commision提成；Pay付款；Order投注；Prize奖金；Return洗码',
	-- 交易金额
	TRADEAMOUNT DOUBLE(18,2) NOT NULL COMMENT '交易金额',
	-- 帐号余额
	ACCOUNTAMOUNT DECIMAL(19,2) COMMENT '帐号余额',
	-- 录入时间
	INPUTTIME DATETIME COMMENT '录入时间',
	REMARK VARCHAR(100),
	PRIMARY KEY (TRADEID)
);


CREATE TABLE T_S_TIMETASK
(
	ID VARCHAR(32) NOT NULL,
	CREATE_BY VARCHAR(32),
	CREATE_DATE DATETIME,
	CREATE_NAME VARCHAR(32),
	CRON_EXPRESSION VARCHAR(100) NOT NULL,
	IS_EFFECT VARCHAR(1) NOT NULL,
	IS_START VARCHAR(1) NOT NULL,
	TASK_DESCRIBE VARCHAR(50) NOT NULL,
	TASK_ID VARCHAR(100) NOT NULL,
	START_TIME DATETIME,
	UPDATE_BY VARCHAR(32),
	UPDATE_DATE DATETIME,
	UPDATE_NAME VARCHAR(32),
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE LOTTERY_ORDER
	ADD FOREIGN KEY (ACCOUNTID)
	REFERENCES ACCOUNT_DETAIL (ACCOUNTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRADE_INFO
	ADD FOREIGN KEY (ACCOUNTID)
	REFERENCES ACCOUNT_DETAIL (ACCOUNTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOTTERY_ORDER
	ADD CONSTRAINT LOTTERY_ORDER_IBFK_1 FOREIGN KEY (ACCOUNTID)
	REFERENCES ACCOUNT_DETAIL (ACCOUNTID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE TRADE_INFO
	ADD CONSTRAINT TRADE_INFO_IBFK_1 FOREIGN KEY (ACCOUNTID)
	REFERENCES ACCOUNT_DETAIL (ACCOUNTID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE LOTTERY_ORDER_DETAIL
	ADD FOREIGN KEY (ORDERID)
	REFERENCES LOTTERY_ORDER (ORDERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOTTERY_ORDER_DETAIL
	ADD CONSTRAINT LOTTERY_ORDER_DETAIL_IBFK_1 FOREIGN KEY (ORDERID)
	REFERENCES LOTTERY_ORDER (ORDERID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE LOTTERY_ORDER
	ADD FOREIGN KEY (ROUNDID)
	REFERENCES LOTTERY_ROUND (ROUNDID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOTTERY_ROUND_ITEM
	ADD FOREIGN KEY (ROUNDID)
	REFERENCES LOTTERY_ROUND (ROUNDID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOTTERY_ORDER
	ADD CONSTRAINT LOTTERY_ORDER_IBFK_2 FOREIGN KEY (ROUNDID)
	REFERENCES LOTTERY_ROUND (ROUNDID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE LOTTERY_ROUND_ITEM
	ADD CONSTRAINT LOTTERY_ROUND_ITEM_IBFK_1 FOREIGN KEY (ROUNDID)
	REFERENCES LOTTERY_ROUND (ROUNDID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;



/* Create Indexes */

CREATE INDEX ACCOUNTID USING BTREE ON LOTTERY_ORDER (ACCOUNTID ASC);
CREATE INDEX ROUNDID USING BTREE ON LOTTERY_ORDER (ROUNDID ASC);
CREATE UNIQUE INDEX ORDERID USING BTREE ON LOTTERY_ORDER_DETAIL (ORDERID ASC, ITEMNO ASC);
CREATE UNIQUE INDEX LOTTERYTYPE USING BTREE ON LOTTERY_ROUND (LOTTERYTYPE ASC, LOTTERYTERM ASC);
CREATE UNIQUE INDEX ROUNDID USING BTREE ON LOTTERY_ROUND_ITEM (ROUNDID ASC, ITEMNO ASC);
CREATE UNIQUE INDEX NAME_GROUP USING BTREE ON TASK_SCHEDULE_JOB (JOB_NAME ASC, JOB_GROUP ASC);
CREATE INDEX ACCOUNTID USING BTREE ON TRADE_INFO (ACCOUNTID ASC);



